Completed css-two-column-layout | Chris Marron
chris-marron/c1222-code-solutions pull request #19
Opened 2022-12-09 19:28 UTC by chris-marron

![image](https://user-images.githubusercontent.com/79817237/206781994-2f051919-0021-435e-a830-de1fa5e20984.png)

2022-12-12 23:49 UTC, codingcodymiller requested changes

2022-12-12 23:49 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
These names are not accurate

2022-12-27 17:11 UTC, codingcodymiller requested changes
Hey Chris! Based on your commit messages, I assume this isn't ready for review yet, so I'm giving you another review, so I know when to come back and give this a proper review.

2023-01-23 21:57 UTC, RobertGardner approved these changes

2023-01-29 07:33 UTC, merged