Completed javascript-primitives-and-variables | Chris Marron
chris-marron/c1222-code-solutions pull request #22
Opened 2022-12-12 19:18 UTC by chris-marron

![image](https://user-images.githubusercontent.com/79817237/207134748-91d66812-2011-410c-927f-8cc20e7c60bd.png)

2022-12-12 23:32 UTC, codingcodymiller requested changes

2022-12-12 23:32 UTC, codingcodymiller commented on javascript-primitives-and-variables/main.js
> +var never =
This should just be `var never;`

2022-12-13 18:13 UTC, chris-marron commented on javascript-primitives-and-variables/main.js
> +var never =
done.

2022-12-13 18:44 UTC, codingcodymiller approved these changes

2022-12-14 20:26 UTC, merged